### ISSUE TITLE
Transparency toogle off-on

### ISSUE THREAD

**Issue by 3dbiomodel** [sketchfab/experiments#57]
Hi Maurice,
thanks for sharing your code for configurator in Sketchfab. I've got a question about it.
I've got a 3D model composed by two parts: Head and Thorax.
I need to upload it in Sketchfab and give to head a different transparency respect Thorax.
I think that this is possible with your configurator, is right?
Is it possible to make a simple "Transparency" slider for Head in html page that i can control to toggle on-off head of my 3D model? 
I noticed your seat configurator and I think: instead color selector it's possible to insert a simple transparency slider?
How can i separate in Sketchfab Head from Thorax?
Thank you
Luca

**Comment by mauricesvay** [comment]
Hi @3dbiomodel ,

you should look at the [Material API](https://sketchfab.com/developers/viewer/functions#api-section-materials). These function should allow you to change the Transparency/Opacity channel of your materials.
To change the opacity of the head and thorax separately, you will need them to have separate materials.

**Comment by 3dbiomodel** [comment]
Hi Maurice,
thanks a lot for your reply.
How can i assign separate materials to head and thorax? This is a think that I have to do inside Sketchfab or in my graphic 3D software? I'm using Rhinoceros.
I seen material API page but I'm not expert and I cannot find an example file to insert an "opacity" slider in Sketchfab 3D Viewer.
Sorry.
Thanks
Luca

**Comment by mauricesvay** [comment]
@3dbiomodel assigning separate materials is something you would do in your 3D software.
We don't have an example for changing the Opacity yet. Maybe someone on the forum has one https://forum.sketchfab.com/.

**Comment by PadreZippo** [comment]
@3dbiomodel as long as you give the materials unique names and apply them to the two parts using Rhino's material manager, it should work. I recommend exporting as OBJ (+MTL) format.

![image](https://user-images.githubusercontent.com/7097291/36809253-66d84e72-1c95-11e8-8d64-650428dd79a7.png)
